---
- name: 시스템 정보 수집
  hosts: work
  gather_facts: true
  become: false

  tasks:
    - name: 호스트네임 출력
      ansible.builtin.debug:
        msg: "호스트네임: {{ ansible_hostname }}"

    - name: IP 주소 출력
      ansible.builtin.debug:
        msg: "IP 주소: {{ ansible_default_ipv4.address }}"

    - name: MAC 주소 출력
      ansible.builtin.debug:
        msg: "MAC 주소: {{ ansible_default_ipv4.macaddress }}"
  
    - name: OS 버전 출력
      ansible.builtin.debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

